# Build and test changes to SeuratWrappers
# Inspired by Jim Hester's Azure Pipelines tests
# https://github.com/jimhester/azuretest

jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    container: rstudio/r-base:3.5-xenial
    steps:
      - script: |
          echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
          mkdir -vp ${R_LIBS_USER}
          sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev libpng-dev libhdf5-dev libboost-all-dev git
        displayName: 'Install R'
      - script: |
          Rscript -e "install.packages('Seurat')"
          Rscript -e "install.packages('rmarkdown')"
          Rscript -e "install.packages('devtools')"
          Rscript -e "install.packages('dplyr')"
        displayName: 'Install Seurat, Rmarkdown, and devtools'
      - script: |
          Rscript -e "install.packages('BiocManager')"
          Rscript -e "BiocManager::install(c('pcaMethods', 'scran'))"
        displayName: "Install Bioconductor dependencies"
      - script: |
          sudo apt-get install -y python3-dev python3-pip
          pip3 install umap-learn
        displayName: "Install python dependencies"
      - script: Rscript -e "devtools::install(dependencies = TRUE)"
        displayName: "Install SeuratWrappers"
      - script: bash test-vignettes.sh
        displayName: "Test Vignettes"
      - task: CopyFiles@2
        inputs:
          contents: 'test-build/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Vignettes
