# Build and test changes to SeuratWrappers
# Inspired by Jim Hester's Azure Pipelines tests
# https://github.com/jimhester/azuretest

jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    container: rstudio/r-base:3.5-xenial
    steps:
      - script: |
          echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
          mkdir -p ${R_LIBS_USER}
          sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev
        displayName: 'Installing R'
      - script: |
          Rscript -e "install.packages('Seurat')"
          Rscript -e "install.packages('rmarkdown')"
          Rscript -e "install.packages('devtools')"
        displayName: 'Installing Seurat, Rmarkdown, and devtools'
      - script: |
          echo "$(pwd -P)"
          ls -l
        displayName: "Testing some stuff"
