# Build and test changes to SeuratWrappers
# Inspired by Jim Hester's Azure Pipelines tests
# https://github.com/jimhester/azuretest

jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    container: satijalab/seurat-wrappers:latest
    steps:
      - script: Rscript -e "devtools::install(dependencies = TRUE)"
        displayName: "Install SeuratWrappers"
      - script: bash test-vignettes.sh
        displayName: "Test Vignettes"
